### ISSUE TITLE
debugger can't be installed on ruby 2.X

### ISSUE THREAD

**Issue by eddiefisher** [cldwalker/debugger#125]
```
ruby -v
ruby 2.1.2p80 (2014-03-01 revision 45231) [x86_64-darwin13.0]
```

```
gem install debugger -v '1.6.6'
Building native extensions.  This could take a while...
ERROR:  Error installing debugger:
    ERROR: Failed to build gem native extension.

    /Users/eddiefisher/.rvm/rubies/ruby-2.1-head/bin/ruby extconf.rb
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
    --with-opt-dir
    --with-opt-include
    --without-opt-include=${opt-dir}/include
    --with-opt-lib
    --without-opt-lib=${opt-dir}/lib
    --with-make-prog
    --without-make-prog
    --srcdir=.
    --curdir
    --ruby=/Users/eddiefisher/.rvm/rubies/ruby-2.1-head/bin/ruby
/Users/eddiefisher/.rvm/rubies/ruby-2.1-head/lib/ruby/2.1.0/fileutils.rb:1573:in `stat': No such file or directory @ rb_file_s_stat - ./212/ruby_debug.h (Errno::ENOENT)
    from /Users/eddiefisher/.rvm/rubies/ruby-2.1-head/lib/ruby/2.1.0/fileutils.rb:1573:in `block in fu_each_src_dest'
    from /Users/eddiefisher/.rvm/rubies/ruby-2.1-head/lib/ruby/2.1.0/fileutils.rb:1587:in `fu_each_src_dest0'
    from /Users/eddiefisher/.rvm/rubies/ruby-2.1-head/lib/ruby/2.1.0/fileutils.rb:1571:in `fu_each_src_dest'
    from /Users/eddiefisher/.rvm/rubies/ruby-2.1-head/lib/ruby/2.1.0/fileutils.rb:399:in `cp'
    from extconf.rb:83:in `block in <main>'
    from extconf.rb:82:in `each'
    from extconf.rb:82:in `<main>'

extconf failed, exit code 1

Gem files will remain installed in /Users/eddiefisher/.rvm/gems/ruby-2.1-head/gems/debugger-1.6.6 for inspection.
Results logged to /Users/eddiefisher/.rvm/gems/ruby-2.1-head/extensions/x86_64-darwin-13/2.1.0/debugger-1.6.6/gem_make.out
```

**Comment by dmcnaught** [comment]
d

**Comment by albe-rosado** [comment]
it is fixed or still ongoing? every time i try to install pry-byebug or byebug or debugger or debugger2 i get this:

ERROR: Failed to build gem native extension.
