### ISSUE TITLE
Unclear install error for ruby 2

### ISSUE THREAD

**Issue by btakita** [cldwalker/debugger#140]
There should be a clear error message that states debugger is not compatible with Ruby 2.

I received the following error when attempting an install:

```
$ gem install debugger
Fetching: columnize-0.9.0.gem (100%)
Successfully installed columnize-0.9.0
Fetching: debugger-ruby_core_source-1.3.7.gem (100%)
Successfully installed debugger-ruby_core_source-1.3.7
Fetching: debugger-linecache-1.2.0.gem (100%)
Successfully installed debugger-linecache-1.2.0
Fetching: debugger-1.6.8.gem (100%)
Building native extensions.  This could take a while...
ERROR:  Error installing debugger:
	ERROR: Failed to build gem native extension.

    /home/phoenix/.rbenv/versions/2.2.0/bin/ruby -r ./siteconf20150119-8346-1n464ri.rb extconf.rb
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/home/phoenix/.rbenv/versions/2.2.0/bin/$(RUBY_BASE_NAME)
/home/phoenix/.rbenv/versions/2.2.0/lib/ruby/2.2.0/fileutils.rb:1391:in `initialize': No such file or directory @ rb_sysopen - ./220/ruby_debug.h (Errno::ENOENT)
	from /home/phoenix/.rbenv/versions/2.2.0/lib/ruby/2.2.0/fileutils.rb:1391:in `open'
	from /home/phoenix/.rbenv/versions/2.2.0/lib/ruby/2.2.0/fileutils.rb:1391:in `copy_file'
	from /home/phoenix/.rbenv/versions/2.2.0/lib/ruby/2.2.0/fileutils.rb:485:in `copy_file'
	from /home/phoenix/.rbenv/versions/2.2.0/lib/ruby/2.2.0/fileutils.rb:402:in `block in cp'
	from /home/phoenix/.rbenv/versions/2.2.0/lib/ruby/2.2.0/fileutils.rb:1570:in `block in fu_each_src_dest'
	from /home/phoenix/.rbenv/versions/2.2.0/lib/ruby/2.2.0/fileutils.rb:1584:in `fu_each_src_dest0'
	from /home/phoenix/.rbenv/versions/2.2.0/lib/ruby/2.2.0/fileutils.rb:1568:in `fu_each_src_dest'
	from /home/phoenix/.rbenv/versions/2.2.0/lib/ruby/2.2.0/fileutils.rb:401:in `cp'
	from extconf.rb:83:in `block in <main>'
	from extconf.rb:82:in `each'
	from extconf.rb:82:in `<main>'

extconf failed, exit code 1

Gem files will remain installed in /home/phoenix/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/debugger-1.6.8 for inspection.
Results logged to /home/phoenix/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/extensions/x86_64-linux/2.2.0-static/debugger-1.6.8/gem_make.out
```

**Comment by cldwalker** [comment]
Thanks for reporting your issue! This is [one of my 14 active issues](https://gh-active-issues.herokuapp.com/#cldwalker/debugger#140). Use that link to check how soon your issue will be answered. Don't forget to check your issue against this project's CONTRIBUTING.md. Cheers.

**Comment by cldwalker** [comment]
A note at the top of the readme already exists. Happy to take a pull for this.

**Comment by quantumpotato** [comment]
+1. Where do I find mkf.log to see errors?

**Comment by sungwoncho** [comment]
+1

**Comment by lumir** [comment]
+1

**Comment by hellobanny** [comment]
+1
